if sys.platform.startswith(‘win32’):
    # Windows code here...
elif sys.platform.startswith('linux'):
    # Linux-specific code here...
elif sys.platform.startswith(‘darwin’):
    # macOS code here...
